### ISSUE TITLE
hyper params

### ISSUE THREAD

**Issue by billhhh** [zeusees/Mnasnet-Pretrained-Model#1]
Thank you for sharing your codes! I have a lit bit many questions to consult you about the pretrained model trained on Imagenet

1. May I know your hyper params (batchsize, lr, weight_decay and how many gpus did you use and how many epochs did the model converge)
2. May I know how did you do data pre-processing(crop methods and other data augmentation)?
3. Did you use Rmsprop as the paper says?
4. May I know did you use your own splitting instead of standard splitting(1281167 for training and 50000 for validation), since your repo says 95:5 split on imagenet? If not, how many imgs for training/testing, could you share your splitting files?

Sorry for a little bit too many questions. Thank you so much!

**Comment by lsy17096535** [comment]
Thanks for your interest. 
1.Training code you can reference https://github.com/chinakook/Mnasnet.MXNet
2.Images splitting by our own mothed.

**Comment by billhhh** [comment]
> Thanks for your interest.
> 1.Training code you can reference https://github.com/chinakook/Mnasnet.MXNet
> 2.Images splitting by our own mothed.

Appreciate your help.

**Comment by lsy17096535** [comment]
standard ILSRVRC 2012 1k classes

**Comment by billhhh** [comment]
May I ask you more about your splitting? Did you split imagenet 1281167 training images into 95:5?

**Comment by szad670401** [comment]
The latest commit has updated with training on standard ILSRVRC 2012

**Comment by billhhh** [comment]
> The latest commit has updated with training on standard ILSRVRC 2012

Thank you for your reply! And is there any difference of your implement between your previous one and latest one?

**Comment by billhhh** [comment]
May I know your training details and hyper params settings?

**Comment by billhhh** [comment]
And how many gpus and batchsize did you use?

**Comment by szad670401** [comment]
I train the model with [gluon-cv](http://gluon-cv.mxnet.io) Mobilenet v2 hyper params with NVIDIA P40 x 8.
